import pandas as pd
import sys
from Bio import SeqIO
cell_type = sys.argv[1]
pairs_folder = sys.argv[2]

####### writes a fasta for all the sequences used for the dataset of one cell type
# uses the file generated by EG_pairs_celltype.py for the variable pairs

genes = {}
enhancers = {}

#dataset with enhancers and gene ids

print('EG_pairs_'+cell_type+'.txt')
pairs = pd.read_csv(pairs_folder+'/EG_pairs_'+cell_type+'.txt', sep = ';')

#fasta generated
fasta_enhencers = open('Fastas/enhancers_'+cell_type+'.fa', "w")
fasta_genes = open('Fastas/genes_'+cell_type+'.fa', "w")


print("processing genes")
for record in SeqIO.parse("Data/fantom_tss_filtered.fa", "fasta"):
	genes[record.id] = record.seq

print("processing enhancers")
for record in SeqIO.parse("Data/fantom_enhancers.fa", "fasta"):
	enhancers[record.id] = record.seq

print("creating new fastas")

processed_enh = []
processed_prom = []

classif_enhancers = open('Classif_dexter/Enhancers/classif_'+cell_type+'.csv', "w")
classif_promoters = open('Classif_dexter/Promoters/classif_'+cell_type+'.csv', "w")

classif_enhancers.write("gene"+'\t'+"col1"+'\n')
classif_promoters.write("gene"+'\t'+"col1"+'\n')


for i in range(len(pairs)):
	e = pairs["Enhancer"].iloc[i]
	p = pairs["Gene"].iloc[i]

	if e not in processed_enh:
		fasta_enhencers.write('>'+ e +'\n'+str(enhancers[e])+'\n')
		classif_enhancers.write(e+'\t'+str(pairs["Interaction"].iloc[i])+'\n')
		processed_enh.append(e)

	if p not in processed_prom:
		fasta_genes.write('>'+ p +'\n'+str(genes[p])+'\n')
		classif_promoters.write(p+'\t'+str(pairs["Interaction"].iloc[i])+'\n')
		processed_prom.append(p)


fasta_genes.close()
fasta_enhencers.close()
classif_enhancers.close()
classif_promoters.close()
